export const categories = [
  { id: 1, name: "home", value: "home" },
  { id: 2, name: "table", value: "table" },
  { id: 3, name: "storage", value: "storage" },
  { id: 4, name: "steel furniture", value: "steel furniture" },
  { id: 5, name: "chair", value: "chair" },
  { id: 6, name: "sofa", value: "sofa" },
  { id: 7, name: "work station", value: "work station" },
  { id: 8, name: "garments", value: "garments" },
  { id: 9, name: "interior", value: "interior" },
];

export const subCategories = [
  { id: 1, name: "bed", value: "bed" },
  { id: 1, name: "dressing table", value: "dressing table" },
  { id: 1, name: "cup board", value: "cup board" },
  { id: 1, name: "Wardrobe", value: "Wardrobe" },
  { id: 1, name: "TV Trolley", value: "tv trolley" },
  { id: 1, name: "Book Shelf", value: "book shelf" },
  { id: 1, name: "Showcase & Corner Shelf", value: "showcase corner shelf" },
  { id: 1, name: "Dinner Wagon", value: "dinner wagon" },
  { id: 1, name: "Dinning Table & Chair", value: "dinning table chair" },
  { id: 2, name: "Director Table", value: "director table" },
  { id: 2, name: "Executive Table", value: "executive table" },
  { id: 2, name: "Manager Table", value: "manager table" },
  { id: 2, name: "Computer Table", value: "computer table" },
  { id: 3, name: "Drawer", value: "drawer" },
  { id: 3, name: "Side Cabinet", value: "side cabinet" },
  { id: 3, name: "File Cabinet", value: "file cabinet" },
  { id: 3, name: "Multipurpose Shelf", value: "multipurpose shelf" },
  { id: 3, name: "Shoe Rack", value: "shoe rack" },
  { id: 4, name: "Almirah", value: "almirah" },
  { id: 4, name: "4 Drawer", value: "4 drawer" },
  { id: 4, name: "3 Drawer", value: "3 drawer" },
  { id: 4, name: "Drawer Cum File Cabinet", value: "drawer cum file cabinet" },
  { id: 4, name: "Slotted Angle Rack", value: "slotted angle rack" },
  { id: 4, name: "Heavy Duty Rack", value: "heavy duty rack" },
  { id: 5, name: "High Back", value: "high back" },
  { id: 5, name: "Medium Back", value: "medium back" },
  { id: 5, name: "Low Back", value: "low back" },
  { id: 5, name: "Fixed/Visitor", value: "fixed visitor" },
  { id: 5, name: "Tool", value: "tool" },
  { id: 5, name: "Auditorium Chair", value: "auditorium chair" },
  { id: 5, name: "Group Chair", value: "group chair" },
  { id: 6, name: "Sofa", value: "sofa" },
  { id: 6, name: "Center Table", value: "center table" },
  { id: 6, name: "Divan", value: "divan" },
  { id: 7, name: "Fabric", value: "fabric" },
  { id: 7, name: "Metal", value: "metal" },
  { id: 7, name: "Others", value: "others" },
  { id: 8, name: "QC Table", value: "qc table" },
  {
    id: 8,
    name: "Center/Cutting/Packing Table",
    value: "center cutting packing table",
  },
  { id: 8, name: "Input/Loading Table", value: "input loading table" },
  { id: 8, name: "Tagging Poly Table", value: "tagging poly table" },
  {
    id: 8,
    name: "Cut Part Inspection Table",
    value: "cut part inspection table",
  },
  {
    id: 8,
    name: "Fabric Relaxing Multi Level Rack",
    value: "fabric relaxing multi level rack",
  },
  { id: 8, name: "Inspection Table", value: "inspection table" },
  { id: 8, name: "Measurement Table", value: "measurement table" },
  { id: 8, name: "Iron Table", value: "iron table" },
  { id: 8, name: "Worker Chair", value: "worker chair" },
  { id: 9, name: "Living", value: "living" },
  { id: 9, name: "Kitchen", value: "kitchen" },
  { id: 9, name: "Office", value: "office" },
  { id: 9, name: "Restaurant", value: "restaurant" },
  { id: 9, name: "Others", value: "others" },
];
